include_guard(GLOBAL)

# add_linked_game_module(<module>
#     [DEFINITIONS <definition>...]
#     [INCLUDE_DIRECTORIES <directory>...]
#     SOURCES <source>...)
#
# Builds a game module (${GAME_MODULE}, ${CGAME_MODULE} or ${UI_MODULE}) for
# linking into the executables: the client gets every module, the dedicated
# server gets ${GAME_MODULE}. VM_Create finds it in vm_linkedModules
# (linked_game_modules.cmake) and uses it instead of a dll or .qvm.
#
# The modules share code (q_shared.c, bg_*.c) with each other and with the
# engine, and each defines vmMain and dllEntry. So the sources are compiled
# twice: once to list the external symbols they define, then again with a
# header forced in that renames each one to <module>_<symbol>.
#
# Game code expects fresh data each time it's loaded. Marker objects before
# and after the module's objects bound its data and bss, which the linker
# lays out in object order, so VM_Create can reset them. That needs the
# module built without LTO and without common symbols.
function(add_linked_game_module MODULE)
    cmake_parse_arguments(ARG "" "" "DEFINITIONS;INCLUDE_DIRECTORIES;SOURCES" ${ARGN})

    if(MSVC)
        message(FATAL_ERROR "Linking game modules into the executable isn't supported with MSVC")
    endif()
    if(NOT CMAKE_NM)
        message(FATAL_ERROR "Linking game modules into the executable needs nm")
    endif()
    get_property(LINKED_MODULES GLOBAL PROPERTY LINKED_GAME_MODULES)
    if(MODULE IN_LIST LINKED_MODULES)
        message(FATAL_ERROR "Only one ${MODULE} can be linked into the executable")
    endif()

    set(SCAN_TARGET ${MODULE}_linked_symbols)
    set(TARGET ${MODULE}_linked)
    set(LINKED_DIR ${CMAKE_BINARY_DIR}/linked)
    set(SYMBOLS_HEADER ${LINKED_DIR}/${MODULE}_symbols.h)

    foreach(MARKER Begin End)
        file(CONFIGURE OUTPUT ${LINKED_DIR}/${MODULE}_linked${MARKER}.c CONTENT [[
// Generated by linked_game_module.cmake. Do not edit.
unsigned char @MODULE@_linkedData@MARKER@[1] = { 1 };
unsigned char @MODULE@_linkedBss@MARKER@[1];
]] @ONLY)
    endforeach()

    add_library(${SCAN_TARGET} OBJECT ${ARG_SOURCES})
    add_library(${TARGET} OBJECT
        ${LINKED_DIR}/${MODULE}_linkedBegin.c # first, so its data comes first
        ${ARG_SOURCES}
        ${SYMBOLS_HEADER}
        ${LINKED_DIR}/${MODULE}_linkedEnd.c)

    foreach(PASS_TARGET ${SCAN_TARGET} ${TARGET})
        target_compile_definitions( ${PASS_TARGET} PRIVATE ${ARG_DEFINITIONS})
        target_include_directories( ${PASS_TARGET} PRIVATE ${ARG_INCLUDE_DIRECTORIES})
        target_compile_options(     ${PASS_TARGET} PRIVATE -fno-common)
        set_target_properties(      ${PASS_TARGET} PROPERTIES INTERPROCEDURAL_OPTIMIZATION OFF)
    endforeach()

    add_custom_command(
        OUTPUT ${SYMBOLS_HEADER}
        COMMAND ${CMAKE_COMMAND}
            -DNM=${CMAKE_NM}
            -DMODULE=${MODULE}
            "-DOBJECTS=$<JOIN:$<TARGET_OBJECTS:${SCAN_TARGET}>,|>"
            -DOUTPUT=${SYMBOLS_HEADER}
            -P ${CMAKE_CURRENT_FUNCTION_LIST_DIR}/linked_game_symbols.cmake
        DEPENDS ${SCAN_TARGET} $<TARGET_OBJECTS:${SCAN_TARGET}>
            ${CMAKE_CURRENT_FUNCTION_LIST_DIR}/linked_game_symbols.cmake
        COMMENT "Listing the symbols of the linked ${MODULE}"
        VERBATIM)

    target_compile_options(${TARGET} PRIVATE -include ${SYMBOLS_HEADER})

    set_property(GLOBAL APPEND PROPERTY LINKED_GAME_MODULES ${MODULE})
endfunction()
