# Writes a header that renames every external symbol a game module's objects
# define, so the module can link into the executable beside the engine and
# the other modules (see linked_game_module.cmake).
#
#   cmake -DNM=<nm> -DMODULE=<module> -DOBJECTS=<object|object|...>
#         -DOUTPUT=<header> -P linked_game_symbols.cmake

cmake_minimum_required(VERSION 3.25)

string(REPLACE "|" ";" OBJECTS "${OBJECTS}")
execute_process(
    COMMAND ${NM} -g -P --defined-only ${OBJECTS}
    OUTPUT_VARIABLE NM_OUTPUT
    ERROR_VARIABLE NM_ERROR # e.g. "no symbols" for an empty object
    RESULT_VARIABLE NM_RESULT)
if(NOT NM_RESULT EQUAL 0)
    message(FATAL_ERROR "${NM} failed: ${NM_ERROR}")
endif()

# POSIX format: "<name> <type> <value> [<size>]", after a "<object>:" line
string(REGEX MATCHALL "[^\r\n]+" LINES "${NM_OUTPUT}")
set(SYMBOLS "")
foreach(LINE IN LISTS LINES)
    if(LINE MATCHES "^([^ ]+) [A-TV-Z] ")
        list(APPEND SYMBOLS ${CMAKE_MATCH_1})
    endif()
endforeach()

# Some platforms (Mach-O, 32-bit Windows) give C names a leading underscore
if("_vmMain" IN_LIST SYMBOLS)
    list(TRANSFORM SYMBOLS REPLACE "^_" "")
elseif(NOT "vmMain" IN_LIST SYMBOLS)
    message(FATAL_ERROR "${MODULE}: no vmMain among the symbols ${NM} lists")
endif()
list(FILTER SYMBOLS INCLUDE REGEX "^[A-Za-z_][A-Za-z0-9_]*$")
list(REMOVE_DUPLICATES SYMBOLS)
list(SORT SYMBOLS)

set(CONTENT "// Generated by linked_game_symbols.cmake. Do not edit.\n")
foreach(SYMBOL IN LISTS SYMBOLS)
    string(APPEND CONTENT "#define ${SYMBOL} ${MODULE}_${SYMBOL}\n")
endforeach()

# Leave the header alone when nothing changed, so the module isn't recompiled
if(EXISTS ${OUTPUT})
    file(READ ${OUTPUT} OLD_CONTENT)
endif()
if(NOT CONTENT STREQUAL "${OLD_CONTENT}")
    file(WRITE ${OUTPUT} "${CONTENT}")
endif()
