# Links the game modules added with add_linked_game_module() into the client
# (all of them) and the dedicated server (${GAME_MODULE}), and generates each
# executable's vm_linkedModules table, which is empty when none are linked.

get_property(LINKED_MODULES GLOBAL PROPERTY LINKED_GAME_MODULES)

function(add_linked_game_modules EXECUTABLE)
    set(DECLARATIONS "")
    set(ENTRIES "")
    foreach(MODULE IN LISTS ARGN)
        target_link_libraries(${EXECUTABLE} PRIVATE ${MODULE}_linked)
        string(CONFIGURE [[
intptr_t @MODULE@_vmMain( int command, int arg0, int arg1, int arg2, int arg3, int arg4, int arg5, int arg6, int arg7, int arg8, int arg9, int arg10, int arg11 );
void @MODULE@_dllEntry( intptr_t (QDECL *syscallptr)( intptr_t arg, ... ) );
extern byte @MODULE@_linkedDataBegin[], @MODULE@_linkedDataEnd[];
extern byte @MODULE@_linkedBssBegin[], @MODULE@_linkedBssEnd[];
]] DECLARATION @ONLY)
        string(CONFIGURE [[
	{ "@MODULE@", @MODULE@_vmMain, @MODULE@_dllEntry,
		@MODULE@_linkedDataBegin, @MODULE@_linkedDataEnd,
		@MODULE@_linkedBssBegin, @MODULE@_linkedBssEnd },
]] ENTRY @ONLY)
        string(APPEND DECLARATIONS "${DECLARATION}")
        string(APPEND ENTRIES "${ENTRY}")
    endforeach()

    set(TABLE ${CMAKE_BINARY_DIR}/linked/${EXECUTABLE}_linked_modules.c)
    file(CONFIGURE OUTPUT ${TABLE} CONTENT [[
// Generated by linked_game_modules.cmake. Do not edit.
#include "@SOURCE_DIR@/qcommon/q_shared.h"
#include "@SOURCE_DIR@/qcommon/qcommon.h"

@DECLARATIONS@
vmLinkedModule_t vm_linkedModules[] = {
@ENTRIES@	{ NULL }
};
]] @ONLY)
    target_sources(${EXECUTABLE} PRIVATE ${TABLE})
endfunction()

if(TARGET ${CLIENT_BINARY})
    add_linked_game_modules(${CLIENT_BINARY} ${LINKED_MODULES})
endif()

if(TARGET ${SERVER_BINARY})
    set(SERVER_LINKED_MODULES ${LINKED_MODULES})
    list(FILTER SERVER_LINKED_MODULES INCLUDE REGEX "^${GAME_MODULE}$")
    add_linked_game_modules(${SERVER_BINARY} ${SERVER_LINKED_MODULES})
endif()
